site_name: IE自学指南
site_url: https://ceclin.github.io/ie-self-learning/
site_author: LinShengxin & ChenJiangxi & GuanRui
site_description: >-
  IE自学指南

repo_name: ie-self-learning
repo_url: https://github.com/ceclin/ie-self-learning
edit_uri: edit/main/docs/

theme:
  name: material
  language: zh


nav:
  - 前言: "index.md"
  - 书籍推荐: "书籍推荐.md"
  - 数学基础类:
      - 微积分: "数学基础类/微积分.md"
      - 线性代数: "数学基础类/线性代数.md"
      - 概率论与数理统计: "数学基础类/概率论与数理统计.md"
      - 运筹学: "数学基础类/运筹学.md"
      - 工程统计学: "数学基础类/工程统计学.md"
  - 工程类:
      - 机械制图: "工程类/机械制图.md"
      - 制造工艺: "工程类/制造工艺.md"
  - 计算机基础类:
      - C++程序设计: "计算机基础类/C++程序设计.md"
      - 数据结构: "计算机基础类/数据结构.md"
      - 数据库原理: "计算机基础类/数据库原理.md"
  - 专业类:
      - 基础工业工程: "专业类/基础工业工程.md"
      - 生产计划与控制: "专业类/生产计划与控制.md"
      - 生产建模与仿真: "专业类/生产建模与仿真.md"
      - 管理学基础: "专业类/管理学基础.md"
      - 人因工程: "专业类/人因工程.md"
      - 优化算法设计: "专业类/优化算法设计.md"
      - 可靠性与维修管理: "专业类/可靠性与维修管理.md"
      - 物流与供应链管理: "专业类/物流与供应链/物流与供应链管理.md"
      - 质量管理学: "专业类/质量管理.md"
      - 服务管理: "专业类/服务管理.md"
      - 大数据分析: "专业类/大数据分析.md"
  - 经验分享:
      - 学习经验: "经验分享/学习经验.md"
      - 保研经验: "经验分享/保研经验.md"
      - 考研经验: "经验分享/考研经验.md"
      - 国外留学: "经验分享/国外留学.md"
      - 就业经验: "经验分享/就业经验.md"
      - 毕业杂谈:
          - 2017-毕业狗眼中的交大工工: "经验分享/毕业杂谈/2017-毕业狗眼中的交大工工.md"
